### ISSUE TITLE
PTV Validation for external user

### ISSUE THREAD

**Issue by fmarco76** [indigo-dc/LiferayPlugIns#22] opened 2017-07-27 12:23 UTC
If the user has no account on Liferay the PTV does not work properly.

**Comment by fmarco76** [comment] 2017-08-28 11:07
Not reproducible

**Comment by tzok** [comment] 2017-08-30 11:16
This problem is reproducible and concerns e.g. users of mobile applications. Namely: when you use just `fgAPIServer` and not Liferay portal. This is because `fgAPIServer` asks `Liferay-IAM` to refresh token and `Liferay-IAM` does not know about non-portal (e.g. mobile) users.

CC: @smamczak @mupsnc

**Comment by fmarco76** [comment] 2017-08-30 11:20
The PTV is to validate a token and not to get a new one. I have tried to validate a token for a user not present in Liferay and it get the correct response. Of course you cannot renew or get a new token, you have to collect the token in the same way you get the original token.

**Comment by tzok** [comment] 2017-08-30 11:29
The scenario is the following:
1. A mobile application generates valid IAM token
2. Using this token, it is able to submit a TOSCA task to FutureGateway (fgAPIServer component)
3. The task remains in SUBMITTED state forever

The situation in 3 is invalid
So why is it happening?

APIServerDaemon is polling Orchestrator for status update. It extracts subject from the token generated in point 1 of the scenario above. Then it sends it over to Liferay-IAM and calls get-token service. But Liferay-IAM responds with "User with subject ... has no access token" and the message has 'token' field set to null. This results in task's status to be frozen in SUBMITTED state.

**Comment by fmarco76** [comment] 2017-08-30 12:13
But in this scenario I cannot see a solution on Liferay side. If there is no user and there is no refresh token there is nothing we can do. The only possible action could be to stop the polling and interrogate the Orchestrator only when the user ask for the results with a token.

This change should go in the fgAPIServer

**Comment by tzok** [comment] 2017-08-30 12:45
Ok, you are right this issue involves different component, but IMHO it is APIServerDaemon. That is where ToscaInterface class is wrongly calling get-token service. So I am closing the issue here and will re-open it there.

**Closed as completed by tzok** 2017-08-30 12:45 UTC
Labels: bug, Medium
